\hypertarget{classChronos_1_1Core_1_1ValidationError}{}\section{Chronos.\+Core.\+Validation\+Error Class Reference}
\label{classChronos_1_1Core_1_1ValidationError}\index{Chronos.\+Core.\+Validation\+Error@{Chronos.\+Core.\+Validation\+Error}}


An Exception for use in \hyperlink{classChronos_1_1Core_1_1Event}{Event} subclasses to indicate that the event is logically invalid.  


Inheritance diagram for Chronos.\+Core.\+Validation\+Error\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classChronos_1_1Core_1_1ValidationError}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
def {\bfseries \+\_\+\+\_\+init\+\_\+\+\_\+} (self, exception\+Message, tags=None)
\end{DoxyCompactItemize}
\subsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
{\bfseries tags}
\end{DoxyCompactItemize}


\subsection{Detailed Description}
An Exception for use in \hyperlink{classChronos_1_1Core_1_1Event}{Event} subclasses to indicate that the event is logically invalid. 

Raising this Exception from within Event\+::\+Raise\+For will still cause the event application to fail, but the failure will not be logged as an error. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
Chronos/Core.\+py\end{DoxyCompactItemize}
